# Generated by Django 5.1.3 on 2024-12-09 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('avg_speed_per_hour', models.IntegerField()),
                ('cost', models.FloatField()),
                ('commission_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Maintenance'), ('decommissioned', 'Decommissioned')], max_length=20)),
            ],
        ),
    ]
