# Generated by Django 5.1.3 on 2024-12-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('4W', '4W [Upto 5mt] [10-14ft bed]'), ('6W', '6W [9-12mt] [18ft bed]'), ('14W', '14W [30mt] [24-28ft bed]'), ('16W_35mt', '16W [35mt] [24-32ft bed]'), ('22W', '22W [42-45mt] [40ft Trailor bed]'), ('18W', '18W [40mt] [40ft Trailor bed]'), ('10W', '10W [16-21mt] [20-22ft bed]'), ('16W_32mt', '16W [32mt] [40ft Trailor bed]'), ('12W', '12W [25mt] [22-24ft bed]'), ('Others', 'Others')], max_length=50),
        ),
    ]
