# Generated by Django 5.1.3 on 2024-12-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_vehicle_vehicle_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.CharField(editable=False, max_length=12, primary_key=True, serialize=False)),
                ('driver_name', models.CharField(max_length=100)),
                ('salary_pm', models.FloatField()),
                ('drivery_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=30)),
            ],
        ),
    ]
