# Generated by Django 5.1.3 on 2024-12-10 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_driver_driver_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.CharField(editable=False, max_length=12, primary_key=True, serialize=False)),
                ('start_point', models.CharField(max_length=100)),
                ('end_point', models.CharField(blank=True, max_length=100, null=True)),
                ('load', models.FloatField()),
                ('margin', models.FloatField(help_text='Percentage between 0-100')),
                ('trip_time', models.DurationField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('trip_distance', models.FloatField(blank=True, null=True)),
                ('driver_cost', models.FloatField(blank=True, null=True)),
                ('driver_allowance', models.FloatField()),
                ('no_restriction_timezone', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_contact',
            field=models.IntegerField(unique=True),
        ),
        migrations.CreateModel(
            name='AdhocCost',
            fields=[
                ('adhoc_cost_id', models.CharField(editable=False, max_length=12, primary_key=True, serialize=False)),
                ('cost', models.FloatField()),
                ('cost_type', models.CharField(choices=[('fuel', 'Fuel'), ('maintenance', 'Maintenance'), ('toll', 'Toll'), ('misc', 'Miscellaneous')], max_length=20)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adhoc_costs', to='vehicles.trip')),
            ],
        ),
    ]
